version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    command: python app.py
    volumes:
      - ./backend/app:/app
    ports:
      - "5001:80"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://mis_g1:mis@db:5432/os_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile # Adjust if your Dockerfile has a different name
    ports:
      - "5173:80" # Nginx inside the container listens on port 80 by default
    depends_on:
      - web

  db:
    build:
      context: ./backend
      dockerfile: init-schema-postgres.dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mis_g1
      - POSTGRES_PASSWORD=mis
      - POSTGRES_DB=os_db

volumes:
  postgres_data:
